language: generic

sudo: required 

services: 
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm run test -- --coverage

after_success:
  - docker build -t terdia07/multi-client ./client
  - docker build -t terdia07/multi-nginx ./nginx
  - docker build -t terdia07/multi-server ./server
  - docker build -t terdia07/multi-worker ./worker

#login to docker cli and push images to hub
  - echo "$DOCKER_PASSWORD" | docker login -u "terdia07" --password-stdin
  - docker push terdia07/multi-client
  - docker push terdia07/multi-nginx
  - docker push terdia07/multi-server
  - docker push terdia07/multi-worker
